const MODEL_TYPES = Object.freeze({
  ML: "ML",
  STATISTICAL_BASELINE: "STATISTICAL_BASELINE",
  HEURISTIC: "HEURISTIC",
  DATA_BLOCKED: "DATA_BLOCKED",
  INSUFFICIENT_DATA: "INSUFFICIENT_DATA",
});

const DATASET_CONTRACTS = Object.freeze({
  fare: {
    target: "finalFare",
    timestamp: "createdAt",
    requiredFields: ["id", "createdAt", "status", "distance", "vehicleType", "finalFare"],
    allowedStatuses: ["COMPLETED"],
    minimumSamples: 100,
    minimumTimeCoverageDays: 30,
    rationale: "100 completed rides provide a minimum across vehicle and distance segments.",
  },
  demand: {
    target: "rideCount",
    timestamp: "createdAt",
    requiredFields: ["id", "createdAt", "status"],
    allowedStatuses: ["REQUESTED", "ACCEPTED", "ARRIVED", "STARTED", "COMPLETED", "CANCELLED"],
    minimumSamples: 168,
    minimumTimeCoverageDays: 28,
    rationale: "Four weeks of hourly history are required to compare hour and weekday effects.",
  },
  cancellation: {
    target: "cancelled",
    timestamp: "createdAt",
    requiredFields: ["id", "createdAt", "status", "distance", "vehicleType", "isScheduled"],
    minimumSamples: 100,
    minimumPositiveSamples: 20,
    minimumNegativeSamples: 20,
    minimumTimeCoverageDays: 30,
    rationale: "Both cancellation classes need at least 20 booking-time examples.",
  },
  vehicle: {
    target: "vehicleType",
    timestamp: "createdAt",
    requiredFields: ["id", "createdAt", "status", "distance", "vehicleType"],
    allowedStatuses: ["COMPLETED"],
    minimumSamples: 100,
    minimumTimeCoverageDays: 30,
    rationale: "Completed rides are required to learn observed vehicle choices.",
  },
  rating: {
    target: "rating",
    timestamp: "createdAt",
    requiredFields: ["id", "createdAt", "rating", "ride"],
    minimumSamples: 100,
    minimumTimeCoverageDays: 30,
    rationale: "Ratings need enough independent completed-ride outcomes for a held-out test.",
  },
  revenue: {
    target: "dailyRevenue",
    timestamp: "createdAt",
    requiredFields: ["id", "createdAt", "amount", "status"],
    allowedStatuses: ["SUCCESS"],
    minimumSamples: 60,
    minimumTimeCoverageDays: 60,
    rationale: "Two months of successful payments are needed for daily seasonality.",
  },
  eta: {
    target: "actualDuration",
    timestamp: "completedAt",
    requiredFields: ["id", "createdAt", "completedAt", "actualDuration", "distance"],
    minimumSamples: 100,
    minimumTimeCoverageDays: 30,
    rationale: "ETA requires observed trip duration, not a routing-provider estimate.",
  },
  weather: {
    target: "rideOutcome",
    timestamp: "createdAt",
    requiredFields: ["id", "createdAt", "weather", "rideOutcome"],
    minimumSamples: 100,
    minimumTimeCoverageDays: 30,
    rationale: "Weather observations must be persisted and joined to ride outcomes.",
  },
  fraud: {
    target: "fraudLabel",
    timestamp: "createdAt",
    requiredFields: ["id", "createdAt", "fraudLabel"],
    minimumSamples: 100,
    minimumPositiveSamples: 20,
    minimumNegativeSamples: 20,
    requiresTrustedLabels: true,
    rationale: "Fraud training requires independently confirmed labels, not anomaly scores.",
  },
});

module.exports = {
  MODEL_TYPES,
  DATASET_CONTRACTS,
};
