const ADMIN_ROLES = require("./adminRoles");
const P = require("./adminPermissions");

const unique = (items) => [...new Set(items)];
const ALL_PERMISSIONS = Object.values(P);

module.exports = Object.freeze({
  [ADMIN_ROLES.SUPER_ADMIN]: ALL_PERMISSIONS,
  [ADMIN_ROLES.ADMIN]: unique([
    P.DASHBOARD_VIEW, P.USER_VIEW, P.USER_MANAGE, P.USER_DELETE, P.USER_EXPORT,
    P.DRIVER_VIEW, P.DRIVER_MANAGE, P.VEHICLE_VIEW, P.VEHICLE_MANAGE,
    P.RIDE_VIEW, P.RIDE_MANAGE, P.PAYMENT_VIEW, P.PAYMENT_MANAGE,
    P.COUPON_VIEW, P.COUPON_MANAGE, P.NOTIFICATION_VIEW, P.NOTIFICATION_MANAGE,
    P.PRICING_VIEW, P.PRICING_MANAGE, P.REPORT_VIEW, P.ANALYTICS_VIEW,
    P.AI_VIEW, P.MAP_VIEW, P.MAP_MANAGE,
    P.AUDIT_LOG_VIEW, P.AUDIT_LOG_EXPORT, P.SETTINGS_VIEW, P.SETTINGS_MANAGE,
    P.SUPPORT_VIEW, P.SUPPORT_MANAGE, P.FILE_VIEW, P.FILE_UPLOAD, P.FILE_MANAGE,
    P.FILE_DELETE, P.ADMIN_VIEW, P.ADMIN_MANAGE, P.SYSTEM_MONITOR,
    P.BACKUP_VIEW, P.BACKUP_CREATE, P.BACKUP_RESTORE, P.BACKUP_DELETE,
    P.ROLE_VIEW, P.PERMISSION_VIEW,
  ]),
  [ADMIN_ROLES.OPERATIONS_MANAGER]: unique([
    P.DASHBOARD_VIEW, P.USER_VIEW, P.USER_MANAGE, P.DRIVER_VIEW, P.DRIVER_MANAGE,
    P.DRIVER_APPROVE, P.DRIVER_SUSPEND, P.VEHICLE_VIEW, P.VEHICLE_MANAGE,
    P.VEHICLE_APPROVE, P.RIDE_VIEW, P.RIDE_MANAGE, P.RIDE_UPDATE,
    P.RIDE_CANCEL, P.SUPPORT_VIEW, P.SUPPORT_MANAGE, P.SYSTEM_MONITOR,
    P.REPORT_VIEW, P.REPORTS_VIEW,
    P.AI_VIEW,
    P.MAP_VIEW, P.MAP_MANAGE,
  ]),
  [ADMIN_ROLES.FINANCE_MANAGER]: unique([
    P.DASHBOARD_VIEW, P.PAYMENT_VIEW, P.PAYMENT_MANAGE, P.PAYMENT_REFUND,
    P.REPORT_VIEW, P.REPORTS_VIEW, P.REPORT_EXPORT, P.ANALYTICS_VIEW,
    P.ANALYTICS_EXPORT,
    P.AI_VIEW,
  ]),
  [ADMIN_ROLES.SUPPORT_EXECUTIVE]: unique([
    P.DASHBOARD_VIEW, P.USER_VIEW, P.USER_MANAGE, P.RIDE_VIEW, P.RIDE_UPDATE,
    P.NOTIFICATION_VIEW, P.NOTIFICATION_SEND, P.SUPPORT_VIEW, P.SUPPORT_MANAGE,
  ]),
  [ADMIN_ROLES.DRIVER_MANAGER]: unique([
    P.DASHBOARD_VIEW, P.DRIVER_VIEW, P.DRIVER_MANAGE, P.DRIVER_APPROVE,
    P.DRIVER_SUSPEND, P.VEHICLE_VIEW, P.VEHICLE_MANAGE, P.VEHICLE_APPROVE,
    P.VEHICLE_DELETE, P.RIDE_VIEW,
  ]),
  [ADMIN_ROLES.MARKETING_MANAGER]: unique([
    P.DASHBOARD_VIEW, P.USER_VIEW, P.COUPON_VIEW, P.COUPON_MANAGE,
    P.COUPON_CREATE, P.COUPON_UPDATE, P.COUPON_DELETE, P.NOTIFICATION_VIEW,
    P.NOTIFICATION_MANAGE, P.NOTIFICATION_SEND, P.NOTIFICATION_BROADCAST,
    P.NOTIFICATION_SCHEDULE, P.REPORT_VIEW, P.REPORTS_VIEW, P.REPORT_EXPORT,
  ]),
});
