const ADMIN_ROLES = Object.freeze({
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  OPERATIONS_MANAGER: "OPERATIONS_MANAGER",
  FINANCE_MANAGER: "FINANCE_MANAGER",
  SUPPORT_EXECUTIVE: "SUPPORT_EXECUTIVE",
  DRIVER_MANAGER: "DRIVER_MANAGER",
  MARKETING_MANAGER: "MARKETING_MANAGER",
});

module.exports = ADMIN_ROLES;