module.exports = Object.freeze({
  USER: "USER",
  DRIVER: "DRIVER",

  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  OPERATIONS_MANAGER: "OPERATIONS_MANAGER",
  FINANCE_MANAGER: "FINANCE_MANAGER",
  SUPPORT_EXECUTIVE: "SUPPORT_EXECUTIVE",
  DRIVER_MANAGER: "DRIVER_MANAGER",
  MARKETING_MANAGER: "MARKETING_MANAGER",
});
