const MIN_HISTORY_DAYS = 7;
const DEFAULT_HISTORY_DAYS = 28;
const MAX_HISTORY_DAYS = 180;

const AI_MODEL_VERSION = "goride-ai-v1";

const AI_STATUS = Object.freeze({
  READY: "READY",
  BLOCKED: "BLOCKED",
  INSUFFICIENT_DATA: "INSUFFICIENT_DATA",
});

const AI_FEATURES = Object.freeze({
  DEMAND_FORECAST: "DEMAND_FORECAST",
  DRIVER_PERFORMANCE: "DRIVER_PERFORMANCE",
  DRIVER_RECOMMENDATION: "DRIVER_RECOMMENDATION",
  ANOMALY_DETECTION: "ANOMALY_DETECTION",
  COUPON_INTELLIGENCE: "COUPON_INTELLIGENCE",
  PRICING_SIGNAL: "PRICING_SIGNAL",
  FARE_INTELLIGENCE: "FARE_INTELLIGENCE",
  SUPPLY_FORECAST: "SUPPLY_FORECAST",
  VEHICLE_RECOMMENDATION: "VEHICLE_RECOMMENDATION",
  RATING_PREDICTION: "RATING_PREDICTION",
  CANCELLATION_PREDICTION: "CANCELLATION_PREDICTION",
  CHURN_PREDICTION: "CHURN_PREDICTION",
  REVENUE_FORECAST: "REVENUE_FORECAST",
  WEATHER_EFFECT: "WEATHER_EFFECT",
  FRAUD_RISK_INTELLIGENCE: "FRAUD_RISK_INTELLIGENCE",
  BUSINESS_RECOMMENDATION_INTELLIGENCE:
    "BUSINESS_RECOMMENDATION_INTELLIGENCE",
  ETA_PREDICTION: "ETA_PREDICTION",
});

const clamp = (value, min, max) => Math.min(Math.max(value, min), max);

module.exports = {
  MIN_HISTORY_DAYS,
  DEFAULT_HISTORY_DAYS,
  MAX_HISTORY_DAYS,
  AI_MODEL_VERSION,
  AI_STATUS,
  AI_FEATURES,
  clamp,
};
